// GENERATED by unity/tools/dump-fish-species.mjs from src/world/fish/FishSpecies.js. Do not edit by hand.
// Anatomy of the fish species, normalized to a total length of 1 (snout tip to the tip of the tail fin); see FishSpecies.js for the
// meaning of every field. The rays and the turtle carry only the entries the skin table reads.
using System.Collections.Generic;

namespace Tidewater.World.Fish
{
	public sealed class Mouth { public double corner, y, tip, protrude; }
	public sealed class Eye { public double u, y, r; }
	public sealed class Seg { public double from, to; public int rays; public bool spiny; public double[][] h; public double[] rake; public double notch; }
	public sealed class Paired { public double u, y, len, bas, spread; public int rays; public string shape; }
	public sealed class Caudal { public string shape; public double len, span, fork; public int rays; }
	public sealed class FinletSpec { public double from, to; public int dorsal, ventral; }

	public sealed class Species
	{
		public string name;
		public int pattern;
		public double body, sec;
		public double[][] top, bot, wid;
		public Mouth mouth;
		public Eye eye;
		public double opercle, scales, scaleVis, lateral, arch;
		public Seg[] dorsal, anal;
		public Paired pectoral, pelvic;
		public Caudal caudal;
		public FinletSpec finlets;
		public int iris;
		public double irid, metal;
	}

	// skin colours (sRGB hex): back, flank, belly, fins, fin edges
	public sealed class Skin { public int back, flank, belly, fin, edge; public double rough; }

	public static class FishSpecies
	{
		public const int P_silverside = 0;
		public const int P_chromis = 1;
		public const int P_grunt = 2;
		public const int P_yellowtail = 3;
		public const int P_tang = 4;
		public const int P_sergeant = 5;
		public const int P_wrasse = 6;
		public const int P_parrot = 7;
		public const int P_angel = 8;
		public const int P_barracuda = 9;
		public const int P_redSnapper = 10;
		public const int P_grouper = 11;
		public const int P_tuna = 12;
		public const int P_mahi = 13;
		public const int P_mullet = 14;
		public const int P_needlefish = 15;
		public const int P_jack = 16;
		public const int P_tarpon = 17;
		public const int P_stingray = 18;
		public const int P_eagleRay = 19;
		public const int P_turtle = 20;

		public static readonly string[] NAMES = { "silverside", "chromis", "grunt", "yellowtail", "tang", "sergeant", "wrasse", "parrot", "angel", "barracuda", "redSnapper", "grouper", "tuna", "mahi", "mullet", "needlefish", "jack", "tarpon", "stingray", "eagleRay", "turtle" };

		public static readonly Dictionary<string, Species> SPECIES = new Dictionary<string, Species>
		{
			{ "silverside", new Species {
				name = "silverside", pattern = 0, body = 0.83, sec = 2.0,
				top = new[] { new[] { 0.0, 0.003 }, new[] { 0.03, 0.016 }, new[] { 0.1, 0.035 }, new[] { 0.25, 0.058 }, new[] { 0.45, 0.068 }, new[] { 0.65, 0.056 }, new[] { 0.85, 0.034 }, new[] { 1.0, 0.026 } },
				bot = new[] { new[] { 0.0, 0.003 }, new[] { 0.03, 0.014 }, new[] { 0.1, 0.032 }, new[] { 0.25, 0.055 }, new[] { 0.45, 0.064 }, new[] { 0.65, 0.05 }, new[] { 0.85, 0.03 }, new[] { 1.0, 0.024 } },
				wid = new[] { new[] { 0.0, 0.003 }, new[] { 0.05, 0.016 }, new[] { 0.2, 0.032 }, new[] { 0.4, 0.036 }, new[] { 0.7, 0.026 }, new[] { 1.0, 0.013 } },
				mouth = new Mouth { corner = 0.07, y = 0.004, tip = 0.006, protrude = 0.0 },
				eye = new Eye { u = 0.1, y = 0.014, r = 0.03 }, opercle = 0.22,
				scales = 0.02, scaleVis = 0.35, lateral = 0.05, arch = 0.1,
				dorsal = new[] { new Seg { from = 0.47, to = 0.53, rays = 5, spiny = true, h = new[] { new[] { 0.0, 0.035 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.5, 0.7 }, notch = 0.125 }, new Seg { from = 0.63, to = 0.74, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.04 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.6, 0.9 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.58, to = 0.78, rays = 12, spiny = false, h = new[] { new[] { 0.0, 0.035 }, new[] { 1.0, 0.018 } }, rake = new[] { 0.6, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.2, y = 0.02, len = 0.1, bas = 0.018, rays = 10, shape = "pointed", spread = 0.4 },
				pelvic = new Paired { u = 0.45, y = 0, len = 0.05, bas = 0, rays = 5, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.17, span = 0.1, fork = 0.5, rays = 13 },
				iris = 0xd8d8c0, irid = 0.8, metal = 0.65,
			} },
			{ "chromis", new Species {
				name = "chromis", pattern = 1, body = 0.76, sec = 2.1,
				top = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.03 }, new[] { 0.08, 0.07 }, new[] { 0.16, 0.12 }, new[] { 0.28, 0.158 }, new[] { 0.42, 0.168 }, new[] { 0.56, 0.153 }, new[] { 0.7, 0.118 }, new[] { 0.84, 0.074 }, new[] { 1.0, 0.05 } },
				bot = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.024 }, new[] { 0.08, 0.054 }, new[] { 0.16, 0.09 }, new[] { 0.28, 0.123 }, new[] { 0.42, 0.133 }, new[] { 0.56, 0.123 }, new[] { 0.7, 0.098 }, new[] { 0.84, 0.064 }, new[] { 1.0, 0.045 } },
				wid = new[] { new[] { 0.0, 0.005 }, new[] { 0.05, 0.03 }, new[] { 0.15, 0.05 }, new[] { 0.3, 0.058 }, new[] { 0.5, 0.053 }, new[] { 0.7, 0.04 }, new[] { 0.9, 0.024 }, new[] { 1.0, 0.02 } },
				mouth = new Mouth { corner = 0.06, y = 0.0, tip = 0.004, protrude = 0.0 },
				eye = new Eye { u = 0.15, y = 0.05, r = 0.033 }, opercle = 0.27,
				scales = 0.028, scaleVis = 0.6, lateral = 0.55, arch = 0.15,
				dorsal = new[] { new Seg { from = 0.3, to = 0.6, rays = 12, spiny = true, h = new[] { new[] { 0.0, 0.05 }, new[] { 0.3, 0.075 }, new[] { 1.0, 0.07 } }, rake = new[] { 0.35, 0.5 }, notch = 0.16 }, new Seg { from = 0.6, to = 0.87, rays = 11, spiny = false, h = new[] { new[] { 0.0, 0.08 }, new[] { 0.5, 0.085 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 1.1 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.56, to = 0.62, rays = 2, spiny = true, h = new[] { new[] { 0.0, 0.04 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.62, to = 0.86, rays = 11, spiny = false, h = new[] { new[] { 0.0, 0.08 }, new[] { 0.4, 0.085 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 1.1 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = -0.01, len = 0.17, bas = 0.035, rays = 17, shape = "pointed", spread = 0.45 },
				pelvic = new Paired { u = 0.33, y = 0, len = 0.12, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.24, span = 0.19, fork = 0.35, rays = 17 },
				iris = 0x4a6a98, irid = 0.15, metal = 0.15,
			} },
			{ "grunt", new Species {
				name = "grunt", pattern = 2, body = 0.81, sec = 2.2,
				top = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.026 }, new[] { 0.08, 0.055 }, new[] { 0.16, 0.093 }, new[] { 0.28, 0.13 }, new[] { 0.42, 0.143 }, new[] { 0.56, 0.135 }, new[] { 0.7, 0.105 }, new[] { 0.84, 0.068 }, new[] { 1.0, 0.048 } },
				bot = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.042 }, new[] { 0.16, 0.072 }, new[] { 0.28, 0.1 }, new[] { 0.42, 0.11 }, new[] { 0.56, 0.103 }, new[] { 0.7, 0.083 }, new[] { 0.84, 0.058 }, new[] { 1.0, 0.045 } },
				wid = new[] { new[] { 0.0, 0.005 }, new[] { 0.05, 0.028 }, new[] { 0.15, 0.05 }, new[] { 0.3, 0.06 }, new[] { 0.5, 0.056 }, new[] { 0.7, 0.042 }, new[] { 0.9, 0.026 }, new[] { 1.0, 0.021 } },
				mouth = new Mouth { corner = 0.1, y = -0.012, tip = -0.006, protrude = 0.0 },
				eye = new Eye { u = 0.14, y = 0.048, r = 0.026 }, opercle = 0.28,
				scales = 0.02, scaleVis = 0.5, lateral = 0.45, arch = 0.15,
				dorsal = new[] { new Seg { from = 0.31, to = 0.6, rays = 12, spiny = true, h = new[] { new[] { 0.0, 0.05 }, new[] { 0.25, 0.085 }, new[] { 1.0, 0.045 } }, rake = new[] { 0.3, 0.55 }, notch = 0.175 }, new Seg { from = 0.6, to = 0.84, rays = 15, spiny = false, h = new[] { new[] { 0.0, 0.055 }, new[] { 0.5, 0.06 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.6, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.62, to = 0.67, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.055 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.67, to = 0.84, rays = 8, spiny = false, h = new[] { new[] { 0.0, 0.065 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.6, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.31, y = -0.02, len = 0.16, bas = 0.03, rays = 16, shape = "pointed", spread = 0.4 },
				pelvic = new Paired { u = 0.34, y = 0, len = 0.1, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.19, span = 0.14, fork = 0.55, rays = 17 },
				iris = 0xc8a040, irid = 0.25, metal = 0.25,
			} },
			{ "yellowtail", new Species {
				name = "yellowtail", pattern = 3, body = 0.77, sec = 2.1,
				top = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.045 }, new[] { 0.16, 0.074 }, new[] { 0.28, 0.099 }, new[] { 0.42, 0.108 }, new[] { 0.56, 0.099 }, new[] { 0.7, 0.077 }, new[] { 0.85, 0.051 }, new[] { 1.0, 0.037 } },
				bot = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.016 }, new[] { 0.08, 0.035 }, new[] { 0.16, 0.058 }, new[] { 0.28, 0.079 }, new[] { 0.42, 0.089 }, new[] { 0.56, 0.082 }, new[] { 0.7, 0.063 }, new[] { 0.85, 0.044 }, new[] { 1.0, 0.034 } },
				wid = new[] { new[] { 0.0, 0.004 }, new[] { 0.05, 0.02 }, new[] { 0.14, 0.036 }, new[] { 0.28, 0.047 }, new[] { 0.45, 0.047 }, new[] { 0.65, 0.038 }, new[] { 0.85, 0.026 }, new[] { 1.0, 0.017 } },
				mouth = new Mouth { corner = 0.1, y = -0.008, tip = -0.003, protrude = 0.003 },
				eye = new Eye { u = 0.12, y = 0.038, r = 0.022 }, opercle = 0.26,
				scales = 0.016, scaleVis = 0.45, lateral = 0.42, arch = 0.12,
				dorsal = new[] { new Seg { from = 0.33, to = 0.6, rays = 10, spiny = true, h = new[] { new[] { 0.0, 0.04 }, new[] { 0.3, 0.06 }, new[] { 1.0, 0.04 } }, rake = new[] { 0.35, 0.55 }, notch = 0.15 }, new Seg { from = 0.6, to = 0.83, rays = 13, spiny = false, h = new[] { new[] { 0.0, 0.045 }, new[] { 1.0, 0.025 } }, rake = new[] { 0.6, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.62, to = 0.66, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.025 }, new[] { 1.0, 0.04 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.66, to = 0.82, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.05 }, new[] { 1.0, 0.025 } }, rake = new[] { 0.6, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = -0.015, len = 0.15, bas = 0.025, rays = 15, shape = "pointed", spread = 0.4 },
				pelvic = new Paired { u = 0.34, y = 0, len = 0.09, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.23, span = 0.165, fork = 0.36, rays = 17 },
				iris = 0xd8a830, irid = 0.35, metal = 0.3,
			} },
			{ "tang", new Species {
				name = "tang", pattern = 4, body = 0.8, sec = 2.0,
				top = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.04 }, new[] { 0.08, 0.1 }, new[] { 0.16, 0.16 }, new[] { 0.28, 0.21 }, new[] { 0.42, 0.232 }, new[] { 0.56, 0.22 }, new[] { 0.7, 0.17 }, new[] { 0.84, 0.095 }, new[] { 1.0, 0.042 } },
				bot = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.035 }, new[] { 0.08, 0.085 }, new[] { 0.16, 0.14 }, new[] { 0.28, 0.19 }, new[] { 0.42, 0.215 }, new[] { 0.56, 0.205 }, new[] { 0.7, 0.16 }, new[] { 0.84, 0.09 }, new[] { 1.0, 0.04 } },
				wid = new[] { new[] { 0.0, 0.005 }, new[] { 0.05, 0.025 }, new[] { 0.15, 0.04 }, new[] { 0.3, 0.046 }, new[] { 0.5, 0.043 }, new[] { 0.7, 0.033 }, new[] { 0.9, 0.02 }, new[] { 1.0, 0.015 } },
				mouth = new Mouth { corner = 0.04, y = 0.006, tip = 0.006, protrude = 0.0 },
				eye = new Eye { u = 0.17, y = 0.085, r = 0.026 }, opercle = 0.27,
				scales = 0.0, scaleVis = 0.0, lateral = 0.75, arch = 0.1,
				dorsal = new[] { new Seg { from = 0.22, to = 0.4, rays = 9, spiny = true, h = new[] { new[] { 0.0, 0.04 }, new[] { 1.0, 0.07 } }, rake = new[] { 0.4, 0.5 }, notch = 0.125 }, new Seg { from = 0.4, to = 0.9, rays = 26, spiny = false, h = new[] { new[] { 0.0, 0.07 }, new[] { 0.6, 0.085 }, new[] { 1.0, 0.045 } }, rake = new[] { 0.55, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.45, to = 0.52, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.52, to = 0.9, rays = 24, spiny = false, h = new[] { new[] { 0.0, 0.07 }, new[] { 0.6, 0.08 }, new[] { 1.0, 0.045 } }, rake = new[] { 0.55, 0.95 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = 0.0, len = 0.15, bas = 0.03, rays = 16, shape = "pointed", spread = 0.45 },
				pelvic = new Paired { u = 0.3, y = 0, len = 0.07, bas = 0, rays = 5, shape = "", spread = 0 },
				caudal = new Caudal { shape = "lunate", len = 0.2, span = 0.19, fork = 0.55, rays = 16 },
				iris = 0x2a3a78, irid = 0.1, metal = 0.05,
			} },
			{ "sergeant", new Species {
				name = "sergeant", pattern = 5, body = 0.79, sec = 2.1,
				top = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.032 }, new[] { 0.08, 0.075 }, new[] { 0.16, 0.13 }, new[] { 0.28, 0.175 }, new[] { 0.42, 0.19 }, new[] { 0.56, 0.176 }, new[] { 0.7, 0.138 }, new[] { 0.84, 0.085 }, new[] { 1.0, 0.055 } },
				bot = new[] { new[] { 0.0, 0.005 }, new[] { 0.03, 0.026 }, new[] { 0.08, 0.06 }, new[] { 0.16, 0.103 }, new[] { 0.28, 0.143 }, new[] { 0.42, 0.155 }, new[] { 0.56, 0.143 }, new[] { 0.7, 0.113 }, new[] { 0.84, 0.073 }, new[] { 1.0, 0.05 } },
				wid = new[] { new[] { 0.0, 0.005 }, new[] { 0.05, 0.03 }, new[] { 0.15, 0.05 }, new[] { 0.3, 0.057 }, new[] { 0.5, 0.052 }, new[] { 0.7, 0.04 }, new[] { 0.9, 0.024 }, new[] { 1.0, 0.02 } },
				mouth = new Mouth { corner = 0.06, y = -0.004, tip = 0.0, protrude = 0.0 },
				eye = new Eye { u = 0.15, y = 0.055, r = 0.03 }, opercle = 0.28,
				scales = 0.026, scaleVis = 0.55, lateral = 0.6, arch = 0.15,
				dorsal = new[] { new Seg { from = 0.3, to = 0.6, rays = 13, spiny = true, h = new[] { new[] { 0.0, 0.05 }, new[] { 0.3, 0.07 }, new[] { 1.0, 0.065 } }, rake = new[] { 0.35, 0.5 }, notch = 0.16 }, new Seg { from = 0.6, to = 0.86, rays = 13, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 0.5, 0.08 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 1.0 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.56, to = 0.62, rays = 2, spiny = true, h = new[] { new[] { 0.0, 0.04 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.62, to = 0.85, rays = 12, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 0.5, 0.078 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 1.0 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = -0.01, len = 0.16, bas = 0.035, rays = 18, shape = "rounded", spread = 0.45 },
				pelvic = new Paired { u = 0.33, y = 0, len = 0.11, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.21, span = 0.17, fork = 0.6, rays = 17 },
				iris = 0xc0b060, irid = 0.1, metal = 0.15,
			} },
			{ "wrasse", new Species {
				name = "wrasse", pattern = 6, body = 0.84, sec = 2.0,
				top = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.042 }, new[] { 0.18, 0.07 }, new[] { 0.32, 0.088 }, new[] { 0.5, 0.09 }, new[] { 0.68, 0.075 }, new[] { 0.85, 0.05 }, new[] { 1.0, 0.042 } },
				bot = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.018 }, new[] { 0.08, 0.038 }, new[] { 0.18, 0.063 }, new[] { 0.32, 0.08 }, new[] { 0.5, 0.082 }, new[] { 0.68, 0.068 }, new[] { 0.85, 0.046 }, new[] { 1.0, 0.04 } },
				wid = new[] { new[] { 0.0, 0.004 }, new[] { 0.05, 0.022 }, new[] { 0.15, 0.038 }, new[] { 0.3, 0.045 }, new[] { 0.5, 0.043 }, new[] { 0.7, 0.034 }, new[] { 0.9, 0.022 }, new[] { 1.0, 0.018 } },
				mouth = new Mouth { corner = 0.07, y = -0.004, tip = 0.0, protrude = 0.0 },
				eye = new Eye { u = 0.13, y = 0.03, r = 0.02 }, opercle = 0.25,
				scales = 0.02, scaleVis = 0.35, lateral = 0.55, arch = 0.25,
				dorsal = new[] { new Seg { from = 0.28, to = 0.5, rays = 8, spiny = true, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.5, 0.6 }, notch = 0.075 }, new Seg { from = 0.5, to = 0.85, rays = 13, spiny = false, h = new[] { new[] { 0.0, 0.038 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.6, 0.8 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.56, to = 0.84, rays = 14, spiny = false, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.028 } }, rake = new[] { 0.6, 0.8 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.24, y = 0.0, len = 0.12, bas = 0.024, rays = 13, shape = "rounded", spread = 0.5 },
				pelvic = new Paired { u = 0.28, y = 0, len = 0.06, bas = 0, rays = 5, shape = "", spread = 0 },
				caudal = new Caudal { shape = "truncate", len = 0.16, span = 0.1, fork = 0.88, rays = 13 },
				iris = 0xd06a40, irid = 0.15, metal = 0.1,
			} },
			{ "parrot", new Species {
				name = "parrot", pattern = 7, body = 0.82, sec = 2.2,
				top = new[] { new[] { 0.0, 0.012 }, new[] { 0.02, 0.035 }, new[] { 0.06, 0.068 }, new[] { 0.12, 0.098 }, new[] { 0.22, 0.128 }, new[] { 0.36, 0.143 }, new[] { 0.5, 0.14 }, new[] { 0.64, 0.118 }, new[] { 0.78, 0.088 }, new[] { 0.9, 0.066 }, new[] { 1.0, 0.058 } },
				bot = new[] { new[] { 0.0, 0.012 }, new[] { 0.02, 0.03 }, new[] { 0.06, 0.055 }, new[] { 0.12, 0.083 }, new[] { 0.22, 0.108 }, new[] { 0.36, 0.123 }, new[] { 0.5, 0.12 }, new[] { 0.64, 0.103 }, new[] { 0.78, 0.078 }, new[] { 0.9, 0.06 }, new[] { 1.0, 0.055 } },
				wid = new[] { new[] { 0.0, 0.01 }, new[] { 0.04, 0.038 }, new[] { 0.12, 0.062 }, new[] { 0.25, 0.077 }, new[] { 0.45, 0.075 }, new[] { 0.65, 0.06 }, new[] { 0.85, 0.04 }, new[] { 1.0, 0.029 } },
				mouth = new Mouth { corner = 0.06, y = -0.018, tip = -0.012, protrude = 0.0 },
				eye = new Eye { u = 0.13, y = 0.052, r = 0.018 }, opercle = 0.27,
				scales = 0.034, scaleVis = 0.75, lateral = 0.55, arch = 0.3,
				dorsal = new[] { new Seg { from = 0.28, to = 0.55, rays = 9, spiny = true, h = new[] { new[] { 0.0, 0.035 }, new[] { 1.0, 0.04 } }, rake = new[] { 0.5, 0.6 }, notch = 0.075 }, new Seg { from = 0.55, to = 0.84, rays = 10, spiny = false, h = new[] { new[] { 0.0, 0.045 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 0.8 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.6, to = 0.64, rays = 2, spiny = true, h = new[] { new[] { 0.0, 0.025 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.5, 0.6 }, notch = 0.075 }, new Seg { from = 0.64, to = 0.83, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.04 }, new[] { 1.0, 0.032 } }, rake = new[] { 0.6, 0.8 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.26, y = 0.0, len = 0.13, bas = 0.03, rays = 13, shape = "rounded", spread = 0.5 },
				pelvic = new Paired { u = 0.3, y = 0, len = 0.07, bas = 0, rays = 5, shape = "", spread = 0 },
				caudal = new Caudal { shape = "lunate", len = 0.18, span = 0.14, fork = 0.62, rays = 15 },
				iris = 0xd09030, irid = 0.1, metal = 0.05,
			} },
			{ "angel", new Species {
				name = "angel", pattern = 8, body = 0.82, sec = 2.0,
				top = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.045 }, new[] { 0.08, 0.11 }, new[] { 0.16, 0.18 }, new[] { 0.28, 0.24 }, new[] { 0.42, 0.262 }, new[] { 0.56, 0.25 }, new[] { 0.7, 0.205 }, new[] { 0.84, 0.13 }, new[] { 1.0, 0.06 } },
				bot = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.04 }, new[] { 0.08, 0.1 }, new[] { 0.16, 0.165 }, new[] { 0.28, 0.225 }, new[] { 0.42, 0.25 }, new[] { 0.56, 0.24 }, new[] { 0.7, 0.198 }, new[] { 0.84, 0.125 }, new[] { 1.0, 0.058 } },
				wid = new[] { new[] { 0.0, 0.005 }, new[] { 0.05, 0.025 }, new[] { 0.15, 0.04 }, new[] { 0.3, 0.046 }, new[] { 0.5, 0.043 }, new[] { 0.7, 0.034 }, new[] { 0.9, 0.02 }, new[] { 1.0, 0.016 } },
				mouth = new Mouth { corner = 0.05, y = 0.004, tip = 0.006, protrude = 0.0 },
				eye = new Eye { u = 0.18, y = 0.075, r = 0.026 }, opercle = 0.3,
				scales = 0.03, scaleVis = 0.9, lateral = 0.7, arch = 0.1,
				dorsal = new[] { new Seg { from = 0.34, to = 0.5, rays = 9, spiny = true, h = new[] { new[] { 0.0, 0.035 }, new[] { 1.0, 0.07 } }, rake = new[] { 0.4, 0.55 }, notch = 0.1 }, new Seg { from = 0.5, to = 0.95, rays = 20, spiny = false, h = new[] { new[] { 0.0, 0.09 }, new[] { 0.7, 0.16 }, new[] { 0.85, 0.2 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.7, 1.2 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.5, to = 0.58, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.4, 0.55 }, notch = 0.1 }, new Seg { from = 0.58, to = 0.95, rays = 18, spiny = false, h = new[] { new[] { 0.0, 0.09 }, new[] { 0.7, 0.15 }, new[] { 0.85, 0.19 }, new[] { 1.0, 0.06 } }, rake = new[] { 0.7, 1.2 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.33, y = 0.0, len = 0.15, bas = 0.035, rays = 18, shape = "rounded", spread = 0.4 },
				pelvic = new Paired { u = 0.32, y = 0, len = 0.14, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "rounded", len = 0.18, span = 0.14, fork = 1.0, rays = 17 },
				iris = 0xd0a020, irid = 0.05, metal = 0.05,
			} },
			{ "barracuda", new Species {
				name = "barracuda", pattern = 9, body = 0.87, sec = 2.0,
				top = new[] { new[] { 0.0, 0.002 }, new[] { 0.03, 0.012 }, new[] { 0.08, 0.025 }, new[] { 0.16, 0.041 }, new[] { 0.28, 0.057 }, new[] { 0.42, 0.064 }, new[] { 0.58, 0.063 }, new[] { 0.72, 0.054 }, new[] { 0.85, 0.04 }, new[] { 0.95, 0.03 }, new[] { 1.0, 0.028 } },
				bot = new[] { new[] { 0.0, 0.002 }, new[] { 0.03, 0.014 }, new[] { 0.08, 0.028 }, new[] { 0.16, 0.044 }, new[] { 0.28, 0.057 }, new[] { 0.42, 0.063 }, new[] { 0.58, 0.061 }, new[] { 0.72, 0.051 }, new[] { 0.85, 0.038 }, new[] { 0.95, 0.028 }, new[] { 1.0, 0.026 } },
				wid = new[] { new[] { 0.0, 0.002 }, new[] { 0.04, 0.014 }, new[] { 0.12, 0.028 }, new[] { 0.25, 0.039 }, new[] { 0.45, 0.044 }, new[] { 0.65, 0.039 }, new[] { 0.85, 0.028 }, new[] { 1.0, 0.018 } },
				mouth = new Mouth { corner = 0.14, y = -0.006, tip = -0.002, protrude = 0.012 },
				eye = new Eye { u = 0.12, y = 0.018, r = 0.012 }, opercle = 0.24,
				scales = 0.008, scaleVis = 0.25, lateral = 0.2, arch = 0.05,
				dorsal = new[] { new Seg { from = 0.44, to = 0.5, rays = 5, spiny = true, h = new[] { new[] { 0.0, 0.055 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.35, 0.6 }, notch = 0.1 }, new Seg { from = 0.74, to = 0.8, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.05 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.75, to = 0.81, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.045 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = -0.015, len = 0.08, bas = 0.016, rays = 12, shape = "pointed", spread = 0.35 },
				pelvic = new Paired { u = 0.47, y = 0, len = 0.05, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.13, span = 0.1, fork = 0.55, rays = 17 },
				iris = 0xb8c0b0, irid = 0.5, metal = 0.55,
			} },
			{ "redSnapper", new Species {
				name = "redSnapper", pattern = 10, body = 0.82, sec = 2.15,
				top = new[] { new[] { 0.0, 0.004 }, new[] { 0.02, 0.02 }, new[] { 0.06, 0.045 }, new[] { 0.12, 0.075 }, new[] { 0.2, 0.11 }, new[] { 0.3, 0.145 }, new[] { 0.42, 0.162 }, new[] { 0.55, 0.155 }, new[] { 0.68, 0.125 }, new[] { 0.8, 0.09 }, new[] { 0.9, 0.062 }, new[] { 1.0, 0.05 } },
				bot = new[] { new[] { 0.0, 0.004 }, new[] { 0.02, 0.018 }, new[] { 0.06, 0.035 }, new[] { 0.12, 0.06 }, new[] { 0.2, 0.09 }, new[] { 0.3, 0.115 }, new[] { 0.42, 0.132 }, new[] { 0.55, 0.128 }, new[] { 0.68, 0.1 }, new[] { 0.8, 0.07 }, new[] { 0.9, 0.054 }, new[] { 1.0, 0.048 } },
				wid = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.02 }, new[] { 0.1, 0.042 }, new[] { 0.2, 0.058 }, new[] { 0.35, 0.066 }, new[] { 0.5, 0.062 }, new[] { 0.65, 0.05 }, new[] { 0.8, 0.034 }, new[] { 0.92, 0.024 }, new[] { 1.0, 0.02 } },
				mouth = new Mouth { corner = 0.11, y = -0.012, tip = -0.004, protrude = 0.004 },
				eye = new Eye { u = 0.135, y = 0.058, r = 0.022 }, opercle = 0.29,
				scales = 0.018, scaleVis = 0.7, lateral = 0.45, arch = 0.15,
				dorsal = new[] { new Seg { from = 0.34, to = 0.62, rays = 10, spiny = true, h = new[] { new[] { 0.0, 0.045 }, new[] { 0.3, 0.085 }, new[] { 1.0, 0.065 } }, rake = new[] { 0.3, 0.5 }, notch = 0.175 }, new Seg { from = 0.62, to = 0.86, rays = 14, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 0.4, 0.078 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.64, to = 0.68, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.03 }, new[] { 1.0, 0.05 } }, rake = new[] { 0.4, 0.5 }, notch = 0.1 }, new Seg { from = 0.68, to = 0.84, rays = 8, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.6, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.34, y = -0.02, len = 0.19, bas = 0.034, rays = 16, shape = "pointed", spread = 0.35 },
				pelvic = new Paired { u = 0.38, y = 0, len = 0.11, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.18, span = 0.13, fork = 0.78, rays = 17 },
				iris = 0xc83020, irid = 0.3, metal = 0.25,
			} },
			{ "grouper", new Species {
				name = "grouper", pattern = 11, body = 0.84, sec = 2.2,
				top = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.03 }, new[] { 0.08, 0.06 }, new[] { 0.15, 0.094 }, new[] { 0.25, 0.128 }, new[] { 0.38, 0.148 }, new[] { 0.52, 0.146 }, new[] { 0.66, 0.126 }, new[] { 0.8, 0.094 }, new[] { 0.92, 0.07 }, new[] { 1.0, 0.06 } },
				bot = new[] { new[] { 0.0, 0.006 }, new[] { 0.03, 0.03 }, new[] { 0.08, 0.06 }, new[] { 0.15, 0.09 }, new[] { 0.25, 0.12 }, new[] { 0.38, 0.137 }, new[] { 0.52, 0.134 }, new[] { 0.66, 0.11 }, new[] { 0.8, 0.08 }, new[] { 0.92, 0.063 }, new[] { 1.0, 0.058 } },
				wid = new[] { new[] { 0.0, 0.006 }, new[] { 0.04, 0.035 }, new[] { 0.12, 0.064 }, new[] { 0.25, 0.079 }, new[] { 0.4, 0.081 }, new[] { 0.6, 0.07 }, new[] { 0.8, 0.05 }, new[] { 1.0, 0.03 } },
				mouth = new Mouth { corner = 0.16, y = -0.022, tip = -0.01, protrude = 0.008 },
				eye = new Eye { u = 0.14, y = 0.07, r = 0.019 }, opercle = 0.33,
				scales = 0.011, scaleVis = 0.4, lateral = 0.55, arch = 0.2,
				dorsal = new[] { new Seg { from = 0.3, to = 0.6, rays = 11, spiny = true, h = new[] { new[] { 0.0, 0.04 }, new[] { 0.3, 0.07 }, new[] { 1.0, 0.055 } }, rake = new[] { 0.3, 0.45 }, notch = 0.21 }, new Seg { from = 0.6, to = 0.85, rays = 17, spiny = false, h = new[] { new[] { 0.0, 0.065 }, new[] { 0.5, 0.075 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.64, to = 0.68, rays = 3, spiny = true, h = new[] { new[] { 0.0, 0.025 }, new[] { 1.0, 0.04 } }, rake = new[] { 0.4, 0.5 }, notch = 0.125 }, new Seg { from = 0.68, to = 0.84, rays = 8, spiny = false, h = new[] { new[] { 0.0, 0.065 }, new[] { 0.5, 0.07 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.33, y = -0.02, len = 0.16, bas = 0.04, rays = 17, shape = "rounded", spread = 0.4 },
				pelvic = new Paired { u = 0.35, y = 0, len = 0.12, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "rounded", len = 0.16, span = 0.11, fork = 1.0, rays = 15 },
				iris = 0x9a8a60, irid = 0.05, metal = 0.0,
			} },
			{ "tuna", new Species {
				name = "tuna", pattern = 12, body = 0.84, sec = 2.0,
				top = new[] { new[] { 0.0, 0.003 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.045 }, new[] { 0.15, 0.075 }, new[] { 0.26, 0.105 }, new[] { 0.38, 0.118 }, new[] { 0.5, 0.115 }, new[] { 0.62, 0.095 }, new[] { 0.74, 0.065 }, new[] { 0.86, 0.035 }, new[] { 0.95, 0.02 }, new[] { 1.0, 0.018 } },
				bot = new[] { new[] { 0.0, 0.003 }, new[] { 0.03, 0.018 }, new[] { 0.08, 0.04 }, new[] { 0.15, 0.065 }, new[] { 0.26, 0.092 }, new[] { 0.38, 0.105 }, new[] { 0.5, 0.102 }, new[] { 0.62, 0.085 }, new[] { 0.74, 0.058 }, new[] { 0.86, 0.032 }, new[] { 0.95, 0.018 }, new[] { 1.0, 0.016 } },
				wid = new[] { new[] { 0.0, 0.003 }, new[] { 0.04, 0.025 }, new[] { 0.12, 0.055 }, new[] { 0.25, 0.08 }, new[] { 0.4, 0.088 }, new[] { 0.55, 0.08 }, new[] { 0.7, 0.058 }, new[] { 0.85, 0.035 }, new[] { 0.95, 0.03 }, new[] { 1.0, 0.02 } },
				mouth = new Mouth { corner = 0.085, y = -0.008, tip = -0.003, protrude = 0.003 },
				eye = new Eye { u = 0.1, y = 0.03, r = 0.022 }, opercle = 0.26,
				scales = 0.0, scaleVis = 0.0, lateral = 0.3, arch = 0.2,
				dorsal = new[] { new Seg { from = 0.3, to = 0.47, rays = 13, spiny = true, h = new[] { new[] { 0.0, 0.07 }, new[] { 0.3, 0.06 }, new[] { 1.0, 0.015 } }, rake = new[] { 0.45, 0.8 }, notch = 0.1 }, new Seg { from = 0.52, to = 0.6, rays = 12, spiny = false, h = new[] { new[] { 0.0, 0.1 }, new[] { 0.5, 0.05 }, new[] { 1.0, 0.015 } }, rake = new[] { 0.75, 1.1 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.56, to = 0.63, rays = 12, spiny = false, h = new[] { new[] { 0.0, 0.09 }, new[] { 0.5, 0.045 }, new[] { 1.0, 0.012 } }, rake = new[] { 0.75, 1.1 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.3, y = 0.0, len = 0.2, bas = 0.03, rays = 12, shape = "falcate", spread = 0.3 },
				pelvic = new Paired { u = 0.32, y = 0, len = 0.06, bas = 0, rays = 5, shape = "", spread = 0 },
				caudal = new Caudal { shape = "lunate", len = 0.16, span = 0.25, fork = 0.25, rays = 19 },
				finlets = new FinletSpec { from = 0.64, to = 0.95, dorsal = 8, ventral = 7 },
				iris = 0xc0a040, irid = 0.9, metal = 0.55,
			} },
			{ "mahi", new Species {
				name = "mahi", pattern = 13, body = 0.83, sec = 2.0,
				top = new[] { new[] { 0.0, 0.016 }, new[] { 0.005, 0.075 }, new[] { 0.013, 0.12 }, new[] { 0.03, 0.148 }, new[] { 0.07, 0.16 }, new[] { 0.18, 0.154 }, new[] { 0.32, 0.134 }, new[] { 0.48, 0.112 }, new[] { 0.64, 0.088 }, new[] { 0.8, 0.06 }, new[] { 0.92, 0.036 }, new[] { 1.0, 0.026 } },
				bot = new[] { new[] { 0.0, 0.01 }, new[] { 0.03, 0.045 }, new[] { 0.08, 0.072 }, new[] { 0.15, 0.09 }, new[] { 0.3, 0.096 }, new[] { 0.45, 0.09 }, new[] { 0.6, 0.078 }, new[] { 0.75, 0.06 }, new[] { 0.9, 0.035 }, new[] { 1.0, 0.022 } },
				wid = new[] { new[] { 0.0, 0.008 }, new[] { 0.04, 0.034 }, new[] { 0.15, 0.05 }, new[] { 0.3, 0.052 }, new[] { 0.5, 0.045 }, new[] { 0.7, 0.035 }, new[] { 0.9, 0.02 }, new[] { 1.0, 0.015 } },
				mouth = new Mouth { corner = 0.075, y = -0.03, tip = -0.02, protrude = 0.004 },
				eye = new Eye { u = 0.085, y = 0.012, r = 0.017 }, opercle = 0.22,
				scales = 0.007, scaleVis = 0.2, lateral = 0.25, arch = 0.25,
				dorsal = new[] { new Seg { from = 0.07, to = 0.97, rays = 44, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 0.08, 0.105 }, new[] { 0.3, 0.08 }, new[] { 0.8, 0.055 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.35, 0.9 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.5, to = 0.97, rays = 24, spiny = false, h = new[] { new[] { 0.0, 0.055 }, new[] { 0.2, 0.06 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.5, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.2, y = -0.02, len = 0.11, bas = 0.022, rays = 16, shape = "pointed", spread = 0.4 },
				pelvic = new Paired { u = 0.22, y = 0, len = 0.08, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.17, span = 0.17, fork = 0.3, rays = 17 },
				iris = 0x8a8a50, irid = 0.6, metal = 0.25,
			} },
			{ "mullet", new Species {
				name = "mullet", pattern = 14, body = 0.82, sec = 2.15,
				top = new[] { new[] { 0.0, 0.008 }, new[] { 0.03, 0.03 }, new[] { 0.08, 0.055 }, new[] { 0.16, 0.08 }, new[] { 0.28, 0.1 }, new[] { 0.42, 0.107 }, new[] { 0.56, 0.1 }, new[] { 0.7, 0.082 }, new[] { 0.84, 0.058 }, new[] { 1.0, 0.044 } },
				bot = new[] { new[] { 0.0, 0.008 }, new[] { 0.03, 0.028 }, new[] { 0.08, 0.05 }, new[] { 0.16, 0.072 }, new[] { 0.28, 0.088 }, new[] { 0.42, 0.093 }, new[] { 0.56, 0.086 }, new[] { 0.7, 0.07 }, new[] { 0.84, 0.05 }, new[] { 1.0, 0.04 } },
				wid = new[] { new[] { 0.0, 0.008 }, new[] { 0.04, 0.036 }, new[] { 0.12, 0.06 }, new[] { 0.25, 0.072 }, new[] { 0.42, 0.072 }, new[] { 0.6, 0.06 }, new[] { 0.8, 0.04 }, new[] { 1.0, 0.024 } },
				mouth = new Mouth { corner = 0.055, y = -0.004, tip = 0.0, protrude = 0.0 },
				eye = new Eye { u = 0.1, y = 0.024, r = 0.02 }, opercle = 0.25,
				scales = 0.024, scaleVis = 0.6, lateral = 0.3, arch = 0.0,
				dorsal = new[] { new Seg { from = 0.44, to = 0.52, rays = 4, spiny = true, h = new[] { new[] { 0.0, 0.06 }, new[] { 1.0, 0.035 } }, rake = new[] { 0.35, 0.6 }, notch = 0.125 }, new Seg { from = 0.66, to = 0.74, rays = 9, spiny = false, h = new[] { new[] { 0.0, 0.06 }, new[] { 1.0, 0.025 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.62, to = 0.72, rays = 11, spiny = false, h = new[] { new[] { 0.0, 0.055 }, new[] { 1.0, 0.025 } }, rake = new[] { 0.55, 0.9 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.27, y = 0.03, len = 0.13, bas = 0.022, rays = 16, shape = "pointed", spread = 0.45 },
				pelvic = new Paired { u = 0.4, y = 0, len = 0.08, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.18, span = 0.13, fork = 0.6, rays = 15 },
				iris = 0xc8b890, irid = 0.5, metal = 0.55,
			} },
			{ "needlefish", new Species {
				name = "needlefish", pattern = 15, body = 0.9, sec = 2.0,
				top = new[] { new[] { 0.0, 0.0015 }, new[] { 0.1, 0.0035 }, new[] { 0.17, 0.007 }, new[] { 0.22, 0.017 }, new[] { 0.28, 0.026 }, new[] { 0.4, 0.032 }, new[] { 0.6, 0.034 }, new[] { 0.78, 0.03 }, new[] { 0.9, 0.02 }, new[] { 1.0, 0.014 } },
				bot = new[] { new[] { 0.0, 0.0015 }, new[] { 0.1, 0.0035 }, new[] { 0.17, 0.007 }, new[] { 0.22, 0.016 }, new[] { 0.28, 0.024 }, new[] { 0.4, 0.03 }, new[] { 0.6, 0.032 }, new[] { 0.78, 0.028 }, new[] { 0.9, 0.019 }, new[] { 1.0, 0.013 } },
				wid = new[] { new[] { 0.0, 0.0015 }, new[] { 0.1, 0.003 }, new[] { 0.18, 0.008 }, new[] { 0.24, 0.02 }, new[] { 0.4, 0.026 }, new[] { 0.7, 0.024 }, new[] { 0.9, 0.016 }, new[] { 1.0, 0.012 } },
				mouth = new Mouth { corner = 0.2, y = 0.0, tip = 0.0, protrude = 0.006 },
				eye = new Eye { u = 0.235, y = 0.008, r = 0.012 }, opercle = 0.3,
				scales = 0.0, scaleVis = 0.0, lateral = -0.7, arch = 0.0,
				dorsal = new[] { new Seg { from = 0.76, to = 0.9, rays = 14, spiny = false, h = new[] { new[] { 0.0, 0.04 }, new[] { 0.2, 0.035 }, new[] { 1.0, 0.018 } }, rake = new[] { 0.6, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.73, to = 0.89, rays = 18, spiny = false, h = new[] { new[] { 0.0, 0.04 }, new[] { 0.2, 0.035 }, new[] { 1.0, 0.018 } }, rake = new[] { 0.6, 0.95 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.33, y = 0.006, len = 0.06, bas = 0.01, rays = 12, shape = "pointed", spread = 0.35 },
				pelvic = new Paired { u = 0.62, y = 0, len = 0.04, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.1, span = 0.06, fork = 0.75, rays = 15 },
				iris = 0xd0d8c8, irid = 0.6, metal = 0.55,
			} },
			{ "jack", new Species {
				name = "jack", pattern = 16, body = 0.78, sec = 2.0,
				top = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.024 }, new[] { 0.08, 0.055 }, new[] { 0.16, 0.088 }, new[] { 0.28, 0.114 }, new[] { 0.42, 0.12 }, new[] { 0.56, 0.107 }, new[] { 0.7, 0.078 }, new[] { 0.84, 0.042 }, new[] { 0.94, 0.024 }, new[] { 1.0, 0.02 } },
				bot = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.046 }, new[] { 0.16, 0.074 }, new[] { 0.28, 0.098 }, new[] { 0.42, 0.105 }, new[] { 0.56, 0.094 }, new[] { 0.7, 0.068 }, new[] { 0.84, 0.037 }, new[] { 0.94, 0.022 }, new[] { 1.0, 0.019 } },
				wid = new[] { new[] { 0.0, 0.004 }, new[] { 0.05, 0.022 }, new[] { 0.15, 0.04 }, new[] { 0.3, 0.048 }, new[] { 0.5, 0.044 }, new[] { 0.7, 0.032 }, new[] { 0.88, 0.02 }, new[] { 1.0, 0.016 } },
				mouth = new Mouth { corner = 0.09, y = -0.006, tip = -0.002, protrude = 0.002 },
				eye = new Eye { u = 0.12, y = 0.03, r = 0.024 }, opercle = 0.26,
				scales = 0.008, scaleVis = 0.2, lateral = 0.35, arch = 0.45,
				dorsal = new[] { new Seg { from = 0.34, to = 0.46, rays = 8, spiny = true, h = new[] { new[] { 0.0, 0.045 }, new[] { 0.3, 0.05 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.4, 0.7 }, notch = 0.15 }, new Seg { from = 0.47, to = 0.84, rays = 27, spiny = false, h = new[] { new[] { 0.0, 0.075 }, new[] { 0.15, 0.06 }, new[] { 1.0, 0.025 } }, rake = new[] { 0.55, 1.05 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.54, to = 0.57, rays = 2, spiny = true, h = new[] { new[] { 0.0, 0.02 }, new[] { 1.0, 0.03 } }, rake = new[] { 0.5, 0.6 }, notch = 0.15 }, new Seg { from = 0.58, to = 0.84, rays = 24, spiny = false, h = new[] { new[] { 0.0, 0.065 }, new[] { 0.15, 0.05 }, new[] { 1.0, 0.022 } }, rake = new[] { 0.55, 1.05 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.29, y = 0.0, len = 0.2, bas = 0.024, rays = 19, shape = "falcate", spread = 0.35 },
				pelvic = new Paired { u = 0.31, y = 0, len = 0.07, bas = 0, rays = 6, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.22, span = 0.19, fork = 0.25, rays = 17 },
				iris = 0xc8c0a0, irid = 0.7, metal = 0.5,
			} },
			{ "tarpon", new Species {
				name = "tarpon", pattern = 17, body = 0.8, sec = 2.05,
				top = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.02 }, new[] { 0.08, 0.045 }, new[] { 0.16, 0.075 }, new[] { 0.28, 0.1 }, new[] { 0.42, 0.11 }, new[] { 0.56, 0.102 }, new[] { 0.7, 0.08 }, new[] { 0.84, 0.052 }, new[] { 1.0, 0.036 } },
				bot = new[] { new[] { 0.0, 0.004 }, new[] { 0.03, 0.022 }, new[] { 0.08, 0.05 }, new[] { 0.16, 0.078 }, new[] { 0.28, 0.098 }, new[] { 0.42, 0.105 }, new[] { 0.56, 0.098 }, new[] { 0.7, 0.077 }, new[] { 0.84, 0.05 }, new[] { 1.0, 0.034 } },
				wid = new[] { new[] { 0.0, 0.004 }, new[] { 0.05, 0.025 }, new[] { 0.15, 0.044 }, new[] { 0.3, 0.052 }, new[] { 0.5, 0.05 }, new[] { 0.7, 0.04 }, new[] { 0.88, 0.026 }, new[] { 1.0, 0.018 } },
				mouth = new Mouth { corner = 0.13, y = 0.004, tip = 0.018, protrude = 0.014 },
				eye = new Eye { u = 0.09, y = 0.028, r = 0.022 }, opercle = 0.22,
				scales = 0.05, scaleVis = 1.0, lateral = 0.05, arch = 0.05,
				dorsal = new[] { new Seg { from = 0.45, to = 0.56, rays = 13, spiny = false, h = new[] { new[] { 0.0, 0.07 }, new[] { 0.6, 0.06 }, new[] { 0.93, 0.05 }, new[] { 1.0, 0.2 } }, rake = new[] { 0.45, 0.95 }, notch = 0.015 } },
				anal = new[] { new Seg { from = 0.64, to = 0.78, rays = 20, spiny = false, h = new[] { new[] { 0.0, 0.07 }, new[] { 0.3, 0.05 }, new[] { 1.0, 0.02 } }, rake = new[] { 0.5, 0.95 }, notch = 0.015 } },
				pectoral = new Paired { u = 0.24, y = -0.06, len = 0.13, bas = 0.02, rays = 13, shape = "pointed", spread = 0.5 },
				pelvic = new Paired { u = 0.43, y = 0, len = 0.08, bas = 0, rays = 9, shape = "", spread = 0 },
				caudal = new Caudal { shape = "forked", len = 0.2, span = 0.17, fork = 0.35, rays = 19 },
				iris = 0xc0c0b0, irid = 0.3, metal = 0.8,
			} },
			{ "stingray", new Species {
				name = "stingray", pattern = 18, body = 1.0, sec = 0,
				mouth = new Mouth { corner = 0.1, y = -0.03, tip = -0.03, protrude = 0 },
				eye = new Eye { u = 0.3, y = 0.05, r = 0.012 }, opercle = 0.4,
				scales = 0.0, scaleVis = 0.0, lateral = 0.0, arch = 0.0,
				iris = 0x606040, irid = 0.0, metal = 0.0,
			} },
			{ "eagleRay", new Species {
				name = "eagleRay", pattern = 19, body = 1.0, sec = 0,
				mouth = new Mouth { corner = 0.1, y = -0.03, tip = -0.03, protrude = 0 },
				eye = new Eye { u = 0.2, y = 0.05, r = 0.014 }, opercle = 0.3,
				scales = 0.0, scaleVis = 0.0, lateral = 0.0, arch = 0.0,
				iris = 0x404040, irid = 0.0, metal = 0.0,
			} },
			{ "turtle", new Species {
				name = "turtle", pattern = 20, body = 1.0, sec = 0,
				mouth = new Mouth { corner = 0.05, y = 0.0, tip = 0.0, protrude = 0 },
				eye = new Eye { u = 0.1, y = 0.04, r = 0.013 }, opercle = 0.2,
				scales = 0.0, scaleVis = 0.0, lateral = 0.0, arch = 0.0,
				iris = 0x302010, irid = 0.0, metal = 0.0,
			} },
		};

		public static readonly Dictionary<string, Skin> SKIN = new Dictionary<string, Skin>
		{
			{ "silverside", new Skin { back = 0x6d8a7a, flank = 0xc4ccce, belly = 0xe6eaea, fin = 0xa8b4ae, edge = 0x98a4a0, rough = 0.3 } },
			{ "chromis", new Skin { back = 0x173a78, flank = 0x2764b8, belly = 0x5588c4, fin = 0x2d62b0, edge = 0xc1424, rough = 0.4 } },
			{ "grunt", new Skin { back = 0xa88a2c, flank = 0xdcbc3a, belly = 0xe6ddb0, fin = 0xd8ac30, edge = 0xc89a24, rough = 0.4 } },
			{ "yellowtail", new Skin { back = 0x566a92, flank = 0x9ea6be, belly = 0xefe6e4, fin = 0xdcc676, edge = 0xe2c040, rough = 0.35 } },
			{ "tang", new Skin { back = 0x12296c, flank = 0x2242a0, belly = 0x2a4aa8, fin = 0x243f96, edge = 0x6aa2dc, rough = 0.45 } },
			{ "sergeant", new Skin { back = 0xc4ac3c, flank = 0xc6cabc, belly = 0xe6e6dc, fin = 0xaaaa98, edge = 0x8a8a80, rough = 0.4 } },
			{ "wrasse", new Skin { back = 0xd4bc1e, flank = 0xe4cc3c, belly = 0xeeeed4, fin = 0xdcca96, edge = 0xc8b070, rough = 0.4 } },
			{ "parrot", new Skin { back = 0x1d6a4c, flank = 0x2e9a7a, belly = 0x6cbc9c, fin = 0x3c9a7a, edge = 0xcc7a5a, rough = 0.4 } },
			{ "angel", new Skin { back = 0xe0e12, flank = 0x121216, belly = 0x16161a, fin = 0xe0e12, edge = 0x2c2410, rough = 0.45 } },
			{ "barracuda", new Skin { back = 0x36464c, flank = 0xb4bcc0, belly = 0xe6eaec, fin = 0x5a6464, edge = 0x2c3434, rough = 0.3 } },
			{ "redSnapper", new Skin { back = 0xb83a3c, flank = 0xd86a6a, belly = 0xeeccc4, fin = 0xcc3c34, edge = 0xb82c24, rough = 0.33 } },
			{ "grouper", new Skin { back = 0x7a6248, flank = 0xb49c7c, belly = 0xd8ccb4, fin = 0x6e5a40, edge = 0x3c3024, rough = 0.4 } },
			{ "tuna", new Skin { back = 0xe1628, flank = 0x66748a, belly = 0xd6dade, fin = 0x1e2630, edge = 0x161a22, rough = 0.28 } },
			{ "mahi", new Skin { back = 0x125c6a, flank = 0xcdb52a, belly = 0xefe29a, fin = 0x2c5c9c, edge = 0x1c4c9c, rough = 0.3 } },
			{ "mullet", new Skin { back = 0x485856, flank = 0xb4bcbe, belly = 0xe6eaea, fin = 0x848c8c, edge = 0x6c7474, rough = 0.33 } },
			{ "needlefish", new Skin { back = 0x36766c, flank = 0xb4cccc, belly = 0xeef2f2, fin = 0x76968e, edge = 0x46666c, rough = 0.3 } },
			{ "jack", new Skin { back = 0x56768c, flank = 0xbcc8d0, belly = 0xe6ecee, fin = 0x86949c, edge = 0x3c444c, rough = 0.3 } },
			{ "tarpon", new Skin { back = 0x364c5c, flank = 0xd4dadc, belly = 0xeef0f2, fin = 0x86949c, edge = 0x4c565c, rough = 0.28 } },
			{ "stingray", new Skin { back = 0x6c604c, flank = 0x7a6c56, belly = 0xd8d6d0, fin = 0x4c4236, edge = 0x8a7c66, rough = 0.5 } },
			{ "eagleRay", new Skin { back = 0x14181e, flank = 0x1c2028, belly = 0xe0e2e2, fin = 0x101418, edge = 0x2a2e36, rough = 0.35 } },
			{ "turtle", new Skin { back = 0x3e3220, flank = 0x86683a, belly = 0xc8b884, fin = 0x4a4238, edge = 0x9a9280, rough = 0.45 } },
		};
	}
}
